In [1]:
from __future__ import division
from sympy import *
init_printing(use_unicode=True)

import numpy as np

import warnings
warnings.filterwarnings("ignore")

Definition of Eigenvectors and Eigenvalues
------------------------------------------

Let $A$ be an $n\times n$ matrix and let $X \in \mathbb{C}^n$ be a nonzero
vector for which $$AX = \lambda X$$ for some scalar
$\lambda$ . Then $\lambda$ is called an **eigenvalue** of the matrix $A$
and $X$ is called an **eigenvector** of $A$ associated with $\lambda$,
or a $\lambda$-eigenvector of $A$.

**Example**: Find the eigenvalues of $A=\left[\begin{array}{ccc} -2 & -2 & -9\\ -1 & 1 & -3\\ 1 & 1 & 4 \end{array}\right]$

 Here we use two methods. The first method is to use the [Matrix](https://docs.sympy.org/latest/tutorial/matrices.html).

In [2]:
A = Matrix([[-2, -2, -9], [-1, 1, -3], [1, 1, 4]])
A

⎡-2  -2  -9⎤
⎢          ⎥
⎢-1  1   -3⎥
⎢          ⎥
⎣1   1   4 ⎦

In [3]:
lamda = symbols('lamda')
p = A.charpoly(lamda)
factor(p)

In [4]:
A.eigenvals()

The second method is to use arrays and [linalg](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html#module-numpy.linalg) from Numpy. This requires converting the Matrix *A* into an [array](https://docs.scipy.org/doc/numpy/reference/generated/numpy.asarray.html).

In [5]:
eigenvectors,_ = np.linalg.eig(np.asarray(A, dtype = int))
eigenvectors

array([1.+1.j, 1.-1.j, 1.+0.j])

Finding Eigenvectors and Eigenvalues
------------------------------------

 

Let $A$ be an $n\times n$ matrix.

1.  The eigenvalues of $A$ are the roots of $c_A(x)$.

2.  The $\lambda$-eigenvectors $X$ are the nontrivial solutions to
    $(\lambda I-A)X=0$.

**Example**: Find the characteristic polynomial, eigenvalues and eigenvectors of the matrix
$$\begin{aligned}
A=\left[\begin{array}{rrr}
4 & 1 & 2 \\ 0 & 3 & -2 \\ 0 & -1 & 2
\end{array}\right].\end{aligned}$$

In [6]:
A = Matrix([[4, 1, 2], [0, 3, -2], [0, -1, 2]])

In [7]:
lamda = symbols('lamda')
p = A.charpoly(lamda)
factor(p)

In [8]:
A.eigenvals()

In [9]:
A.eigenvects()

⎡⎛      ⎡⎡-1⎤⎤⎞  ⎛      ⎡⎡1⎤  ⎡0 ⎤⎤⎞⎤
⎢⎜      ⎢⎢  ⎥⎥⎟  ⎜      ⎢⎢ ⎥  ⎢  ⎥⎥⎟⎥
⎢⎜1, 1, ⎢⎢1 ⎥⎥⎟, ⎜4, 2, ⎢⎢0⎥, ⎢-2⎥⎥⎟⎥
⎢⎜      ⎢⎢  ⎥⎥⎟  ⎜      ⎢⎢ ⎥  ⎢  ⎥⎥⎟⎥
⎣⎝      ⎣⎣1 ⎦⎦⎠  ⎝      ⎣⎣0⎦  ⎣1 ⎦⎦⎠⎦

Alternatively,

In [10]:
eigenvalues, eigenvectors = np.linalg.eig(np.asarray(A, dtype = int))
eigenvalues, eigenvectors

(array([4., 4., 1.]),
 array([[ 1.        ,  0.        , -0.57735027],
        [ 0.        ,  0.89442719,  0.57735027],
        [ 0.        , -0.4472136 ,  0.57735027]]))

Diagonalizing a Matrix
----------------------

Let $A$ be an $n\times n$ matrix. The process of finding an
**invertible** matrix $P$ and a **diagonal** matrix $D$ so that
$A=PDP^{-1}$ is referred to as **diagonalizing** the matrix $A$, and $P$
is called the **diagonalizing** matrix for $A$.

The key to diagonalizing a matrix (finding the matrices $P$ and $D$)
lies in the eigenvectors and eigenvalues of the matrix $A$.

### Eigenvectors and Diagonalizable Matrices
Let $A$ be an $n\times n$ matrix.

1.  $A$ is diagonalizable if and only if it has eigenvectors
    $X_1, X_2, \ldots, X_n$ so that
    $P = \left[\begin{array}{cccc} X_1 & X_2 & \cdots & X_n \end{array}\right]$
    is invertible.

2.  If $P$ is invertible, then
    $$P^{-1}AP=\mathrm{Diag}(\lambda_1, \lambda_2, \ldots, \lambda_n )$$
    where $\lambda_i$ is the eigenvalue of $A$ corresponding to the
    eigenvector $X_i$, i.e., $AX_i=\lambda_i X_i$.

**Example**: Let $A =\left[\begin{array}{ccc} 1 & 0 & 0\\ 0 & 2 & -1\\ 0 & 1 & 2 \end{array}\right]$. Find an invertible matrix $P$ and a diagonal matrix $D$ such that $P^{-1}AP = D$.

In [11]:
A = Matrix([[1, 0, 0], [0, 2, -1], [0, 1 ,2]])
A

⎡1  0  0 ⎤
⎢        ⎥
⎢0  2  -1⎥
⎢        ⎥
⎣0  1  2 ⎦

In [12]:
lamda = symbols('lamda')
p = A.charpoly(lamda)
factor(p)

The eigenvalues of $A$ are the the roots of $c_A(\lambda)$:

In [13]:
A.eigenvals()

The correcponding eigenvectors:

In [14]:
A.eigenvects()

⎡⎛      ⎡⎡1⎤⎤⎞  ⎛          ⎡⎡0 ⎤⎤⎞  ⎛          ⎡⎡0⎤⎤⎞⎤
⎢⎜      ⎢⎢ ⎥⎥⎟  ⎜          ⎢⎢  ⎥⎥⎟  ⎜          ⎢⎢ ⎥⎥⎟⎥
⎢⎜1, 1, ⎢⎢0⎥⎥⎟, ⎜2 - ⅈ, 1, ⎢⎢-ⅈ⎥⎥⎟, ⎜2 + ⅈ, 1, ⎢⎢ⅈ⎥⎥⎟⎥
⎢⎜      ⎢⎢ ⎥⎥⎟  ⎜          ⎢⎢  ⎥⎥⎟  ⎜          ⎢⎢ ⎥⎥⎟⎥
⎣⎝      ⎣⎣0⎦⎦⎠  ⎝          ⎣⎣1 ⎦⎦⎠  ⎝          ⎣⎣1⎦⎦⎠⎦

diagonalizing matrix for $A$

In [15]:
P, D=A.diagonalize()
P

⎡1  0   0⎤
⎢        ⎥
⎢0  -ⅈ  ⅈ⎥
⎢        ⎥
⎣0  1   1⎦

In [16]:
D

⎡1    0      0  ⎤
⎢               ⎥
⎢0  2 - ⅈ    0  ⎥
⎢               ⎥
⎣0    0    2 + ⅈ⎦

In [17]:
P**-1

⎡1   0    0 ⎤
⎢           ⎥
⎢    ⅈ      ⎥
⎢0   ─   1/2⎥
⎢    2      ⎥
⎢           ⎥
⎢   -ⅈ      ⎥
⎢0  ───  1/2⎥
⎣    2      ⎦

We can verify our results

In [18]:
simplify(P*D*P**-1)

⎡1  0  0 ⎤
⎢        ⎥
⎢0  2  -1⎥
⎢        ⎥
⎣0  1  2 ⎦

Raising a Matrix to a High Power
--------------------------------

Suppose we have a matrix $A$ and we want to find $A^{20}$. You could try
to multiply A with itself 20 times; however, this is computationally
extremely intensive and it is not recommended. We also can
diagonalization to compute high powers of a matrix relatively easily.

Suppose $A$ is diagonalizable, so there is an invertible matrix $P$ such
that $P^{-1} AP = D$. We can rearrange this equation to
$$\begin{aligned}
&P^{-1} AP = D,\\
\Rightarrow\quad & PP^{-1} AP = PD,\\
\Rightarrow \quad &  AP=PD,\\
\Rightarrow\quad & APP^{-1}=PDP^{-1},\\
\Rightarrow \quad &  A=PDP^{-1}.\end{aligned}$$ Now, consider $A^2$.
Since $A=PDP^{-1}$, it follows that $$\begin{aligned}
A^2=\underbrace{PDP^{-1}}_{A}\underbrace{PDP^{-1}}_{A}=PD^2P^{-1}.\end{aligned}$$
Similarly, $$\begin{aligned}
A^3=\underbrace{PDP^{-1}}_{A}\underbrace{PDP^{-1}}_{A}\underbrace{PDP^{-1}}_{A}=PD^3P^{-1}.\end{aligned}$$
In general, $$\begin{aligned}
A^n=\underbrace{PDP^{-1}PDP^{-1}\ldots PDP^{-1}}_{n\text{ times}}=PD^nP^{-1}.\end{aligned}$$
Therefore, we have reduced the problem to finding $D^n$. In order to
compute $D^n$ , then because $D$ is diagonal we only need to raise every
entry on the main diagonal of $D$ to the power of $n$.

**Example**:
Let $A =\begin{bmatrix} 1 & 1 & 0\\ 0 & 2 & 0\\ 0 & 2 & 1 \end{bmatrix}$. Find $A^{10}$.

In [19]:
A = Matrix([[1, 1, 0],[ 0, 2, 0],[ 0, 2, 1]])
A

⎡1  1  0⎤
⎢       ⎥
⎢0  2  0⎥
⎢       ⎥
⎣0  2  1⎦

In [20]:
lamda = symbols('lamda')
p = A.charpoly(lamda)
factor(p)

The eigenvalues of $A$ are the the roots of $c_A(\lambda)$:

In [21]:
A.eigenvals()

The correcponding eigenvectors:

In [22]:
A.eigenvects()

⎡⎛      ⎡⎡1⎤  ⎡0⎤⎤⎞  ⎛      ⎡⎡1/2⎤⎤⎞⎤
⎢⎜      ⎢⎢ ⎥  ⎢ ⎥⎥⎟  ⎜      ⎢⎢   ⎥⎥⎟⎥
⎢⎜1, 2, ⎢⎢0⎥, ⎢0⎥⎥⎟, ⎜2, 1, ⎢⎢1/2⎥⎥⎟⎥
⎢⎜      ⎢⎢ ⎥  ⎢ ⎥⎥⎟  ⎜      ⎢⎢   ⎥⎥⎟⎥
⎣⎝      ⎣⎣0⎦  ⎣1⎦⎦⎠  ⎝      ⎣⎣ 1 ⎦⎦⎠⎦

diagonalizing matrix for $A$

In [23]:
P, D=A.diagonalize()
P

⎡1  0  1⎤
⎢       ⎥
⎢0  0  1⎥
⎢       ⎥
⎣0  1  2⎦

In [24]:
D

⎡1  0  0⎤
⎢       ⎥
⎢0  1  0⎥
⎢       ⎥
⎣0  0  2⎦

In [25]:
P**-1

⎡1  -1  0⎤
⎢        ⎥
⎢0  -2  1⎥
⎢        ⎥
⎣0  1   0⎦

We can verify our results

In [26]:
simplify(P*D*P**-1)

⎡1  1  0⎤
⎢       ⎥
⎢0  2  0⎥
⎢       ⎥
⎣0  2  1⎦

Therefore, $A^{10}$

In [27]:
P*(D**(10))*P**-1

⎡1  1023  0⎤
⎢          ⎥
⎢0  1024  0⎥
⎢          ⎥
⎣0  2046  1⎦

In [28]:
n = symbols('n')
P*(D**(n))*P**-1

⎡     n        ⎤
⎢1   2  - 1   0⎥
⎢              ⎥
⎢       n      ⎥
⎢0     2      0⎥
⎢              ⎥
⎢      n       ⎥
⎣0  2⋅2  - 2  1⎦

Orthogonal Matrices
----------------------------
$A$ real $n\times n$ matrix $U$ is called an orthogonal matrix if $UU^T =U^T U = I$.
\end{definition}

**Example**:
Show the matrix $U =\left[\begin{array}{ccc} 1 & 0 & 0\\ 0 & 0 & -1\\ 0 & -1 & 0 \end{array}\right]$ is orthogonal.

In [29]:
U=Matrix([[1,0,0],[0,0,-1],[0,-1,0]])
U

⎡1  0   0 ⎤
⎢         ⎥
⎢0  0   -1⎥
⎢         ⎥
⎣0  -1  0 ⎦

In [30]:
U*U**-1

⎡1  0  0⎤
⎢       ⎥
⎢0  1  0⎥
⎢       ⎥
⎣0  0  1⎦

In [31]:
U**-1*U

⎡1  0  0⎤
⎢       ⎥
⎢0  1  0⎥
⎢       ⎥
⎣0  0  1⎦

Hence, this matrix is orthogonal

Determinant of Orthogonal Matrices
---------------------------------------------------------------------
Suppose $U$ is an orthogonal matrix. Then, $det(U) = 1$ or $det(U) = -1$.

**Example**

In [32]:
U=Matrix([[1,0,0],[0,0,-1],[0,-1,0]])
U

⎡1  0   0 ⎤
⎢         ⎥
⎢0  0   -1⎥
⎢         ⎥
⎣0  -1  0 ⎦

$det(U)$=

In [33]:
det(U)

We know that a matrix $A$ is called symmetric if $A = A^T$. If the
matrix $A$ is symmetric, then we can actually find such a matrix $P$
that is an orthogonal matrix of eigenvectors. Thus $P^{-1}$ is simply
its transpose $P^T$, and $P^T AP$ is diagonal. When this happens we say
that $A$ is **orthogonally diagonalizable**.

An $n\times n$ matrix $A$ is said to be **orthogonally diagonalizable**
when an orthogonal matrix $P$ can be found such that
$P^{-1} AP = P^T AP$ is diagonal.

**Example**:
Find an orthogonal matrix $P$ such that $P^{T} AP$ is diagonal, where $A = \left[\begin{array}{ccc} 1 & 0 & 0\\ 0 & 3 & 1\\ 0 & 1 & 3 \end{array}\right]$.

In [34]:
A = Matrix([[1,0,0],[0,3,1],[0,1,3]])
A

⎡1  0  0⎤
⎢       ⎥
⎢0  3  1⎥
⎢       ⎥
⎣0  1  3⎦

In [35]:
lamda = symbols('lamda')
p = A.charpoly(lamda)
factor(p)

The eigenvalues of $A$ are the the roots of $c_A(\lambda)$:

In [36]:
A.eigenvals()

The correcponding eigenvectors:

In [37]:
A.eigenvects()

⎡⎛      ⎡⎡1⎤⎤⎞  ⎛      ⎡⎡0 ⎤⎤⎞  ⎛      ⎡⎡0⎤⎤⎞⎤
⎢⎜      ⎢⎢ ⎥⎥⎟  ⎜      ⎢⎢  ⎥⎥⎟  ⎜      ⎢⎢ ⎥⎥⎟⎥
⎢⎜1, 1, ⎢⎢0⎥⎥⎟, ⎜2, 1, ⎢⎢-1⎥⎥⎟, ⎜4, 1, ⎢⎢1⎥⎥⎟⎥
⎢⎜      ⎢⎢ ⎥⎥⎟  ⎜      ⎢⎢  ⎥⎥⎟  ⎜      ⎢⎢ ⎥⎥⎟⎥
⎣⎝      ⎣⎣0⎦⎦⎠  ⎝      ⎣⎣1 ⎦⎦⎠  ⎝      ⎣⎣1⎦⎦⎠⎦

diagonalizing matrix for $A$

In [38]:
P, D=A.diagonalize()
P[:,1]=P[:,1]/sqrt(2)
P[:,2]=P[:,2]/sqrt(2)
P

⎡1   0    0 ⎤
⎢           ⎥
⎢   -√2   √2⎥
⎢0  ────  ──⎥
⎢    2    2 ⎥
⎢           ⎥
⎢    √2   √2⎥
⎢0   ──   ──⎥
⎣    2    2 ⎦

In [39]:
D

⎡1  0  0⎤
⎢       ⎥
⎢0  2  0⎥
⎢       ⎥
⎣0  0  4⎦

We can verify our results

In [40]:
simplify(P*D*transpose(P))

⎡1  0  0⎤
⎢       ⎥
⎢0  3  1⎥
⎢       ⎥
⎣0  1  3⎦

In [41]:
simplify(transpose(P)*A*P)

⎡1  0  0⎤
⎢       ⎥
⎢0  2  0⎥
⎢       ⎥
⎣0  0  4⎦